from .start import start_router
from .get_words import words_router
from .learn_personal import learn_router
from .save_personal import save_personal_router
from .save_general import save_general_router
from .delete import delete_router
from .competition import compete_router
from .learn_general import global_learn_router
from .get_loggs import logging_router
